version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: team3
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: my-secret-pw
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - db

  node:
    build: 
       context: .
       dockerfile: Dockerfileg

    restart: always
    ports:
      - "2000:2000"
    depends_on:
      - db

  vue:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:80"
    environment:
      NODE_ENV: development